### ISSUE TITLE
PublishNuGetsSettings namespace cannot be found

### ISSUE THREAD

**Issue by eyescreamxx** [cake-contrib/Cake.ExtendedNuGet#33] opened 2019-08-08 07:56 UTC
Hi there is an issue in v2.1.1

![image](https://user-images.githubusercontent.com/10457623/62685230-d51b3680-b9f4-11e9-814d-2460e8898d1e.png)

**Comment by gep13** [comment] 2019-08-08 07:59
@alvinbriones232 can you provide a small sample Cake script that exhibits this problem?  That would be the easiest way to allow a reproduction of the problem.  Information about what version of Cake you are using, and what runner you are using, i.e. Cake.exe, Cake Global Tool, etc, would also help.

**Comment by alvinbriones232** [comment] 2019-08-08 08:06
void PushAllNuGetPkgs(BuildEnvironment env, string src)
{
    var pushSettings = new PublishNuGetsSettings
    {
        ForcePush   = true,
        MaxAttempts = 2
    };
}

**Comment by alvinbriones232** [comment] 2019-08-08 08:08
using cake 0.22.0

**Comment by gep13** [comment] 2019-08-08 08:10
Has this problem only just started happening? If so, are you pinned to a specific version of Cake.ExtendedNuGet? If not, the recent new release may no longer work unless you upgrade to a newer version of Cake.

**Comment by alvinbriones232** [comment] 2019-08-08 08:12
I tried using cake version 0.34.0 and still not working, yes this issue occurs just today.

**Comment by alvinbriones232** [comment] 2019-08-08 08:14
For now we will use our v1.0.0.27, also this issue occurs in 2.1.0

**Comment by augustoproiete** [comment] 2021-01-27 20:34
Hey @eyescreamxx It's been a while and you might have been using a newer version of Cake already, but just wanted to let you know I tested with both `Cake 0.38.5` and `1.0.0-rc0002` and was not able to reproduce the error above.

build.cake
```csharp
#addin nuget:?package=Cake.ExtendedNuGet&version=2.1.1

var pushSettings = new PublishNuGetsSettings
{
    ForcePush = true,
    MaxAttempts = 2
};

Information("ForcePush: {0}", pushSettings.ForcePush);
Information("MaxAttempts: {0}", pushSettings.MaxAttempts);
```

Both RTM and RC versions of Cake produce the expected output:

```powershell
ForcePush: True
MaxAttempts: 2
```

I'm closing this as resolved. Please feel free to reopen if you find a way to reproduce it.

**Closed by augustoproiete** 2021-01-27 20:34 UTC
